/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadDocumentRouteImport } from './routes/api/upload-document'
import { Route as ApiReviewSpecRouteImport } from './routes/api/review-spec'
import { Route as ApiIngestDocumentRouteImport } from './routes/api/ingest-document'
import { Route as ApiImproveSectionRouteImport } from './routes/api/improve-section'
import { Route as ApiGenerateSpecV2RouteImport } from './routes/api/generate-spec-v2'
import { Route as ApiGenerateSpecRouteImport } from './routes/api/generate-spec'
import { Route as ApiDeleteDocumentRouteImport } from './routes/api/delete-document'
import { Route as ApiChatMessageRouteImport } from './routes/api/chat-message'
import { Route as ApiChatAttachRouteImport } from './routes/api/chat-attach'
import { Route as ApiAgentTurnRouteImport } from './routes/api/agent-turn'
import { Route as AuthenticatedSignupRequestsRouteImport } from './routes/_authenticated/signup-requests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsManagementRouteImport } from './routes/_authenticated/projects-management'
import { Route as AuthenticatedProductRouteImport } from './routes/_authenticated/product'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedAgentConversationsIndexRouteImport } from './routes/_authenticated/agent-conversations.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedEditorIdRouteImport } from './routes/_authenticated/editor.$id'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedAgentConversationsIdRouteImport } from './routes/_authenticated/agent-conversations.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadDocumentRoute = ApiUploadDocumentRouteImport.update({
  id: '/api/upload-document',
  path: '/api/upload-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewSpecRoute = ApiReviewSpecRouteImport.update({
  id: '/api/review-spec',
  path: '/api/review-spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestDocumentRoute = ApiIngestDocumentRouteImport.update({
  id: '/api/ingest-document',
  path: '/api/ingest-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImproveSectionRoute = ApiImproveSectionRouteImport.update({
  id: '/api/improve-section',
  path: '/api/improve-section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSpecV2Route = ApiGenerateSpecV2RouteImport.update({
  id: '/api/generate-spec-v2',
  path: '/api/generate-spec-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSpecRoute = ApiGenerateSpecRouteImport.update({
  id: '/api/generate-spec',
  path: '/api/generate-spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteDocumentRoute = ApiDeleteDocumentRouteImport.update({
  id: '/api/delete-document',
  path: '/api/delete-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessageRoute = ApiChatMessageRouteImport.update({
  id: '/api/chat-message',
  path: '/api/chat-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAttachRoute = ApiChatAttachRouteImport.update({
  id: '/api/chat-attach',
  path: '/api/chat-attach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent-turn',
  path: '/api/agent-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignupRequestsRoute =
  AuthenticatedSignupRequestsRouteImport.update({
    id: '/signup-requests',
    path: '/signup-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsManagementRoute =
  AuthenticatedProjectsManagementRouteImport.update({
    id: '/projects-management',
    path: '/projects-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductRoute = AuthenticatedProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentConversationsIndexRoute =
  AuthenticatedAgentConversationsIndexRouteImport.update({
    id: '/agent-conversations/',
    path: '/agent-conversations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditorIdRoute = AuthenticatedEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentConversationsIdRoute =
  AuthenticatedAgentConversationsIdRouteImport.update({
    id: '/agent-conversations/$id',
    path: '/agent-conversations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/product': typeof AuthenticatedProductRoute
  '/projects-management': typeof AuthenticatedProjectsManagementRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signup-requests': typeof AuthenticatedSignupRequestsRoute
  '/api/agent-turn': typeof ApiAgentTurnRoute
  '/api/chat-attach': typeof ApiChatAttachRoute
  '/api/chat-message': typeof ApiChatMessageRoute
  '/api/delete-document': typeof ApiDeleteDocumentRoute
  '/api/generate-spec': typeof ApiGenerateSpecRoute
  '/api/generate-spec-v2': typeof ApiGenerateSpecV2Route
  '/api/improve-section': typeof ApiImproveSectionRoute
  '/api/ingest-document': typeof ApiIngestDocumentRoute
  '/api/review-spec': typeof ApiReviewSpecRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/agent-conversations/$id': typeof AuthenticatedAgentConversationsIdRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/agent-conversations/': typeof AuthenticatedAgentConversationsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/product': typeof AuthenticatedProductRoute
  '/projects-management': typeof AuthenticatedProjectsManagementRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signup-requests': typeof AuthenticatedSignupRequestsRoute
  '/api/agent-turn': typeof ApiAgentTurnRoute
  '/api/chat-attach': typeof ApiChatAttachRoute
  '/api/chat-message': typeof ApiChatMessageRoute
  '/api/delete-document': typeof ApiDeleteDocumentRoute
  '/api/generate-spec': typeof ApiGenerateSpecRoute
  '/api/generate-spec-v2': typeof ApiGenerateSpecV2Route
  '/api/improve-section': typeof ApiImproveSectionRoute
  '/api/ingest-document': typeof ApiIngestDocumentRoute
  '/api/review-spec': typeof ApiReviewSpecRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/agent-conversations/$id': typeof AuthenticatedAgentConversationsIdRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/agent-conversations': typeof AuthenticatedAgentConversationsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/product': typeof AuthenticatedProductRoute
  '/_authenticated/projects-management': typeof AuthenticatedProjectsManagementRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/signup-requests': typeof AuthenticatedSignupRequestsRoute
  '/api/agent-turn': typeof ApiAgentTurnRoute
  '/api/chat-attach': typeof ApiChatAttachRoute
  '/api/chat-message': typeof ApiChatMessageRoute
  '/api/delete-document': typeof ApiDeleteDocumentRoute
  '/api/generate-spec': typeof ApiGenerateSpecRoute
  '/api/generate-spec-v2': typeof ApiGenerateSpecV2Route
  '/api/improve-section': typeof ApiImproveSectionRoute
  '/api/ingest-document': typeof ApiIngestDocumentRoute
  '/api/review-spec': typeof ApiReviewSpecRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/_authenticated/agent-conversations/$id': typeof AuthenticatedAgentConversationsIdRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/editor/$id': typeof AuthenticatedEditorIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/agent-conversations/': typeof AuthenticatedAgentConversationsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/pending-approval'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/agents'
    | '/billing'
    | '/dashboard'
    | '/documents'
    | '/organization'
    | '/product'
    | '/projects-management'
    | '/settings'
    | '/signup-requests'
    | '/api/agent-turn'
    | '/api/chat-attach'
    | '/api/chat-message'
    | '/api/delete-document'
    | '/api/generate-spec'
    | '/api/generate-spec-v2'
    | '/api/improve-section'
    | '/api/ingest-document'
    | '/api/review-spec'
    | '/api/upload-document'
    | '/agent-conversations/$id'
    | '/chat/$threadId'
    | '/editor/$id'
    | '/projects/$projectId'
    | '/agent-conversations/'
    | '/projects/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/pending-approval'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/agents'
    | '/billing'
    | '/dashboard'
    | '/documents'
    | '/organization'
    | '/product'
    | '/projects-management'
    | '/settings'
    | '/signup-requests'
    | '/api/agent-turn'
    | '/api/chat-attach'
    | '/api/chat-message'
    | '/api/delete-document'
    | '/api/generate-spec'
    | '/api/generate-spec-v2'
    | '/api/improve-section'
    | '/api/ingest-document'
    | '/api/review-spec'
    | '/api/upload-document'
    | '/agent-conversations/$id'
    | '/chat/$threadId'
    | '/editor/$id'
    | '/projects/$projectId'
    | '/agent-conversations'
    | '/projects'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/pending-approval'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/agents'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/organization'
    | '/_authenticated/product'
    | '/_authenticated/projects-management'
    | '/_authenticated/settings'
    | '/_authenticated/signup-requests'
    | '/api/agent-turn'
    | '/api/chat-attach'
    | '/api/chat-message'
    | '/api/delete-document'
    | '/api/generate-spec'
    | '/api/generate-spec-v2'
    | '/api/improve-section'
    | '/api/ingest-document'
    | '/api/review-spec'
    | '/api/upload-document'
    | '/_authenticated/agent-conversations/$id'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/editor/$id'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/agent-conversations/'
    | '/_authenticated/projects/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
  ApiChatAttachRoute: typeof ApiChatAttachRoute
  ApiChatMessageRoute: typeof ApiChatMessageRoute
  ApiDeleteDocumentRoute: typeof ApiDeleteDocumentRoute
  ApiGenerateSpecRoute: typeof ApiGenerateSpecRoute
  ApiGenerateSpecV2Route: typeof ApiGenerateSpecV2Route
  ApiImproveSectionRoute: typeof ApiImproveSectionRoute
  ApiIngestDocumentRoute: typeof ApiIngestDocumentRoute
  ApiReviewSpecRoute: typeof ApiReviewSpecRoute
  ApiUploadDocumentRoute: typeof ApiUploadDocumentRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-document': {
      id: '/api/upload-document'
      path: '/api/upload-document'
      fullPath: '/api/upload-document'
      preLoaderRoute: typeof ApiUploadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-spec': {
      id: '/api/review-spec'
      path: '/api/review-spec'
      fullPath: '/api/review-spec'
      preLoaderRoute: typeof ApiReviewSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-document': {
      id: '/api/ingest-document'
      path: '/api/ingest-document'
      fullPath: '/api/ingest-document'
      preLoaderRoute: typeof ApiIngestDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/improve-section': {
      id: '/api/improve-section'
      path: '/api/improve-section'
      fullPath: '/api/improve-section'
      preLoaderRoute: typeof ApiImproveSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-spec-v2': {
      id: '/api/generate-spec-v2'
      path: '/api/generate-spec-v2'
      fullPath: '/api/generate-spec-v2'
      preLoaderRoute: typeof ApiGenerateSpecV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-spec': {
      id: '/api/generate-spec'
      path: '/api/generate-spec'
      fullPath: '/api/generate-spec'
      preLoaderRoute: typeof ApiGenerateSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-document': {
      id: '/api/delete-document'
      path: '/api/delete-document'
      fullPath: '/api/delete-document'
      preLoaderRoute: typeof ApiDeleteDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-message': {
      id: '/api/chat-message'
      path: '/api/chat-message'
      fullPath: '/api/chat-message'
      preLoaderRoute: typeof ApiChatMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-attach': {
      id: '/api/chat-attach'
      path: '/api/chat-attach'
      fullPath: '/api/chat-attach'
      preLoaderRoute: typeof ApiChatAttachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-turn': {
      id: '/api/agent-turn'
      path: '/api/agent-turn'
      fullPath: '/api/agent-turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/signup-requests': {
      id: '/_authenticated/signup-requests'
      path: '/signup-requests'
      fullPath: '/signup-requests'
      preLoaderRoute: typeof AuthenticatedSignupRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects-management': {
      id: '/_authenticated/projects-management'
      path: '/projects-management'
      fullPath: '/projects-management'
      preLoaderRoute: typeof AuthenticatedProjectsManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/product': {
      id: '/_authenticated/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AuthenticatedProductRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-conversations/': {
      id: '/_authenticated/agent-conversations/'
      path: '/agent-conversations'
      fullPath: '/agent-conversations/'
      preLoaderRoute: typeof AuthenticatedAgentConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor/$id': {
      id: '/_authenticated/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof AuthenticatedEditorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-conversations/$id': {
      id: '/_authenticated/agent-conversations/$id'
      path: '/agent-conversations/$id'
      fullPath: '/agent-conversations/$id'
      preLoaderRoute: typeof AuthenticatedAgentConversationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedProductRoute: typeof AuthenticatedProductRoute
  AuthenticatedProjectsManagementRoute: typeof AuthenticatedProjectsManagementRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSignupRequestsRoute: typeof AuthenticatedSignupRequestsRoute
  AuthenticatedAgentConversationsIdRoute: typeof AuthenticatedAgentConversationsIdRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedEditorIdRoute: typeof AuthenticatedEditorIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedAgentConversationsIndexRoute: typeof AuthenticatedAgentConversationsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedProductRoute: AuthenticatedProductRoute,
  AuthenticatedProjectsManagementRoute: AuthenticatedProjectsManagementRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSignupRequestsRoute: AuthenticatedSignupRequestsRoute,
  AuthenticatedAgentConversationsIdRoute:
    AuthenticatedAgentConversationsIdRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedEditorIdRoute: AuthenticatedEditorIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedAgentConversationsIndexRoute:
    AuthenticatedAgentConversationsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
  ApiChatAttachRoute: ApiChatAttachRoute,
  ApiChatMessageRoute: ApiChatMessageRoute,
  ApiDeleteDocumentRoute: ApiDeleteDocumentRoute,
  ApiGenerateSpecRoute: ApiGenerateSpecRoute,
  ApiGenerateSpecV2Route: ApiGenerateSpecV2Route,
  ApiImproveSectionRoute: ApiImproveSectionRoute,
  ApiIngestDocumentRoute: ApiIngestDocumentRoute,
  ApiReviewSpecRoute: ApiReviewSpecRoute,
  ApiUploadDocumentRoute: ApiUploadDocumentRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
